name: miatracker
description: M.I.A Tracker - Maintenance Inventory Asset Tracker
publish_to: 'none'

version: 1.0.0+5

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  supabase_flutter: ^2.6.0
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  pdf: ^3.10.8
  path_provider: ^2.1.1
  open_file: ^3.3.2


  # Dependencias para funcionalidad de inventario con imágenes
  image_picker: ^1.0.7
  permission_handler: ^11.3.1
  cached_network_image: ^3.3.1
  image: ^4.1.7
  path: ^1.9.0

  # Dependencias para códigos QR y de barras
  qr_flutter: ^4.1.0
  barcode_widget: ^2.0.4
  mobile_scanner: ^5.1.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/logomiatracker.png
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_foreground: assets/app_icon/logomiatracker.png
  adaptive_icon_background: "#2B5F8C"

flutter_native_splash:
  color: "#2B5F8C"
  image: assets/app_icon/logomiatracker.png
  ios: true
  android: true
  android_12:
    image: assets/app_icon/logomiatracker.png
    color: "#2B5F8C"
